### ISSUE TITLE
DaggerAllComponent Error

### ISSUE THREAD

**Issue by pharidali** [jachness/blockcalls#3]
Their is no DaggerAllComponent file on modules folder but you include DaggerAllComponent on AppContext file.

Please Check it.

thank you

**Comment by jachness** [comment]
Hi Pharidali,
This DaggerAllComponent class is auto-generated by the Dagger framework from the com.jachness.blockcalls.modules.AllComponent interface. You just rebuild the project and it will be created.

**Comment by jachness** [comment]
I'm closing this since it's not an issue in the source code.

**Comment by pharidali** [comment]
hello still couldnt fixed . please help me

**Comment by pharidali** [comment]
please help me. i got same error when trying to rebuild
