### ISSUE TITLE
Alternative to Playstore download

### ISSUE THREAD

**Issue by IzzySoft** [jachness/blockcalls#7]
Would you consider attaching the `.apk` to the corresponding `/releases`, so folks can get them without Playstore? Of course ven better to promote it to the official F-Droid repo :innocent: But until then, I could offer to serve it [via mine](https://android.izzysoft.de/repo) – but for that, the APK would be needed :stuck_out_tongue_winking_eye:

**Comment by jachness** [comment]
I'll consider attach the apk in future releases!

**Comment by IzzySoft** [comment]
Thanks for considering that, @jachness – maybe you could also consider re-opening this issue and closing it when the first `.apk` is there, so I (and everyone else subscribing to this issue) get a notification then?

**Comment by dbrgn** [comment]
I would also welcome an F-Droid release. Surprisingly, there is currently no call blocker app at all on F-Droid.
